# Generated by Django 5.0.2 on 2024-02-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/')),
                ('brand', models.CharField(max_length=256)),
                ('model', models.CharField(max_length=256)),
                ('fuel', models.CharField(choices=[('GASOLINE', 'Gasoline'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid'), ('BENZIN', 'Benzin')], max_length=30)),
                ('mileage', models.PositiveBigIntegerField()),
                ('price_per_hour', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('price_per_day', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('price_per_month', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
