# Generated by Django 5.0.1 on 2024-02-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=256, verbose_name='бренд')),
                ('description', models.CharField(max_length=256, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='car/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
