# Generated by Django 5.0.1 on 2024-02-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=256, verbose_name='ФИО')),
                ('description', models.CharField(max_length=256, verbose_name='Описание')),
                ('position', models.CharField(max_length=256, verbose_name='Должность')),
                ('image', models.ImageField(upload_to='team/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
    ]
